services:
  lead-qualifier-agent:
    image: tifma/lead-qualifier-agent:latest
    ports:
      - "8080:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
